export const description = {
   inputsFields: {
      placeholder: 'name',
      passwordPlaceholder: 'hasło',
      emailPlaceholder: 'email',
   },
   form: {
      requiredEmail: 'Email jest wymagany',
      messageEmail: 'Podaj swój adres email',
      requiredPass: 'Hasło jest wymagane',
   },
   userInterview: {
      userReservation: 'Rezerwacja do:',
      courseEvaluation: 'Ocena przejścia kursu',
      activityAssessment: 'Ocena aktywności i zaangażowania na kursie',
      codeEvaluation: 'Ocena kodu w projekcie własnym',
      scrumAssessment: 'Ocena pracy w zespole Scrum',
      preferWork: 'Preferowane miejscie pracy',
      targetPlace: 'Docelowe miasto, gdzie kandydat chce pracować',
      contractType: 'Oczekiwany typ kontraktu',
      targetSalary: 'Oczekiwanie miesięcczne wynagrodzenie netto',
      practice: 'Zgoda na odbycie bezpłatnych praktyk/stażu na początek',
      experience: 'Komercyjne dościadcznie w programowaniu',
   },
   buttons: {
      showCv: 'pokaż cv',
      disinterest: 'brak zainteresowania',
      hired: 'zatrudniony',
      bookCall: 'zarezerwuj rozmowe',
      logOut: 'wyloguj',
      logIn: 'Zaloguj się',
      account: 'konto',
      forgotPass: 'zapomniałeś hasła ?',
   },
   studentPortfolio: {
      rating: 'Oceny',
      expectation: 'Oczekiwanie w stosunku do zatrudnienia',
      education: 'Edukacja',
      courses: 'Kursy',
      experience: 'Doświadczenie zawodowe',
      portfolio: 'Portfolio',
      groupProject: 'Projekt w zespole scrumowym',
      ownProject: 'Projekt na zaliczenie',
      aboutMe: 'O mnie',
   },
   filterModal: {
      courseEvaluation: 'ocena przejścia kursu',
      activityAssessment: 'ocena aktywności na kursie',
      codeEvaluation: 'ocena kodu w pojekcie własnym',
      jobEvaluation: 'ocena pracy w zespole SCRUM',
      typeOfWork: 'preferowane miejsce pracy',
      typeOfContract: 'preferowany typ kontraktu',
      salary: 'Oczekiwane wynagrodzenie miesięczne netto',
      internship: 'zgoda na odbycie bezpłatnych praktyk/stażu na początek',
      experience:
         'Ilośc miesięcy doświacznia komercyjnego kandydata w programowaniu',
   },
}
