export const description = {
   inputsFields: {
      filterPlaceholder: 'Wyszukaj...',
      passwordPlaceholder: 'hasło',
      emailPlaceholder: 'email',
   },
   form: {
      requiredEmail: 'Email jest wymagany',
      messageEmail: 'Podaj poprawny adres email',
      requiredPass: 'Hasło jest wymagane',
      requiredField: 'Pole obowiązkowe',
      messageLongText: 'Wpis jest za długi',
      messageBigNumber: 'Wartość jest za duża',
      messageSmallNumber: 'Wartość jest za mała',
   },
   userInterview: {
      userReservation: 'rezerwacja do:',
      courseEvaluation: 'ocena przejścia kursu',
      activityAssessment: 'ocena aktywności i zaangażowania na kursie',
      codeEvaluation: 'ocena kodu w projekcie własnym',
      scrumAssessment: 'ocena pracy w zespole Scrum',
      preferWork: 'preferowane miejsce pracy',
      targetPlace: 'docelowe miasto, gdzie kandydat chce pracować',
      contractType: 'oczekiwany typ kontraktu',
      targetSalary: 'oczekiwanie miesięczne wynagrodzenie netto',
      practice: 'zgoda na odbycie bezpłatnych praktyk/stażu na początek',
      experience: 'komercyjne doświadczenie w programowaniu',
   },
   buttons: {
      showCv: 'pokaż cv',
      disinterest: 'brak zainteresowania',
      hired: 'zatrudniony',
      bookCall: 'zarezerwuj rozmowe',
      logOut: 'wyloguj',
      logIn: 'Zaloguj się',
      account: 'konto',
      forgotPass: 'zapomniałeś hasła ?',
      addHr: 'dodaj nowego HR',
      addStudent: 'dodaj nowego studenta',
      importStudents: 'Zaimportuj studentów z pliku',
      importHr: 'Zaimportuj HR z pliku',
      annual: 'anuluj',
      search: 'wyszukaj',
      filter: 'Filtrowanie',
   },
   studentPortfolio: {
      rating: 'oceny',
      expectation: 'oczekiwanie w stosunku do zatrudnienia',
      educationDescribe: 'edukacja',
      coursesDescribe: 'kursy',
      experienceDescribe: 'doświadczenie zawodowe',
      portfolio: 'portfolio',
      groupProject: 'projekt w zespole scrumowym',
      ownProject: 'projekt na zaliczenie',
      aboutMe: 'o mnie',
      backFromModal: 'wróć',
      office: 'biuro',
      ready_to_move: 'możliwość realokacji',
      remote: 'praca zdalna',
      hybrid: 'praca hybrydowa',
      any: 'dowolne',
      uop: 'Umowa o pracę',
      b2b: 'B2B',
      uz_uod: 'umowa cywilno prawna',
      yes: 'tak',
      no: 'nie',
   },
   editCv: {
      addProjectBtn: 'dodaj nowy projekt',
      sendFormBtn: 'wyślij zmiany',
      firstNameDesc: 'imię:',
      lastNameDesc: 'nazwisko:',
      githubNickDesc: 'nick na githubie:',
      emailDesc: 'e-mail:',
      telDesc: 'telefon:',
      firstNameErrorMessage: 'imię może mieć maksymalnie 18 znaków',
      lastNameErrorMessage: 'nazwisko może mieć maksymalnie 30 znaków',
      emailErrorMessage: 'e-mail niepoprawny',
      githubNickErrorMessage:
         'Nick na githubie może mieć maksymalnie 60 znaków',
      telErrorMessage: 'telefon może mieć maksymalnie 15 znaków',
      targetWorkCityErrorMessage:
         'docelowe miasto może mieć maksymalnie 30 znaków',
      expectedSalaryErrorMessage:
         'wynagrodzenie może mieć maksymalnie 5 znaków',
      monthsOfCommercialExpErrorMessage:
         'doświadczenie w programowaniu może mieć maksymalnie 11 znaków',
   },
   filterModal: {
      courseEvaluation: 'ocena przejścia kursu',
      activityAssessment: 'ocena aktywności na kursie',
      codeEvaluation: 'ocena kodu w pojekcie własnym',
      jobEvaluation: 'ocena pracy w zespole SCRUM',
      typeOfWork: 'preferowane miejsce pracy',
      typeOfContract: 'preferowany typ kontraktu',
      salary: 'Oczekiwane wynagrodzenie miesięczne netto',
      internship: 'zgoda na odbycie bezpłatnych praktyk/stażu na początek',
      experience:
         'Ilośc miesięcy doświacznia komercyjnego kandydata w programowaniu',
      filterName: 'Filtrowanie',
      clearAll: 'Wyczyść wszystko',
   },
   navigation: {
      availableStudents: 'Dostępni kursanci',
      toReview: 'Do rozmowy',
   },
}
